version: "3"
services:
    postgres:
        image: postgres:latest
        container_name: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=cloud
        restart: always
        networks:
            - cloud-network

    cloud:
        image: cloud:latest
        container_name: cloud
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        restart: always
        volumes:
            - /var/tmp
        networks:
            - cloud-network

networks:
    cloud-network:
        driver: bridge

volumes:
    pgdata:
